### ISSUE TITLE
rename to core

### ISSUE THREAD

**Issue by jonyrock** [chartwerk/base#16]
I propose to rename this repo to "core"
@rozetko

**Comment by jonyrock** [comment]
After renaming `Base` to `Pod`, we started little by little understand the design of the lib. So if we rename this to `core` then it will express the idea of this repo: actually the fundamental basics of chartwerk, right?

What you @rozetko @VargBurz think?

Btw, what we thought to call as "rack", maybe we name "base" now.

**Comment by rozetko** [comment]
@jonyrock sounds good!

**Comment by VargBurz** [comment]
@jonyrock @rozetko  good!
